Admin management
ccuffs/sac pull request #42
Opened 2019-09-24 04:37 UTC by arufonsekun

As alterações introduzidas por essa _pull_ _request_ são:

- Link `Gerenciar Permissões > Usuários`  no _dropdown_ `ações`, OBS: _dropdown_ só irá aparecer caso o usuário logado for admin;
- Esse link leva pra nova rota do grupo `admin`: http://localhost/sac/admin/permissoes,
- Na _view_ retornada por essa rota estarão listados os usuários que fizeram login no site, nela o administrador tem a possibilidade de mudar as permissões dos usuários;
- Uma nova _user role_ foi criada: co-organizador;

2019-09-24 04:40 UTC, mateusKoppe commented
Show! Vou fazer codereview, até amanhã finalizo! Obrigado pelo PR!

PR referente a issue #10

2019-09-24 05:05 UTC, mateusKoppe requested changes
Cara, ficou muito foda esses cards e esse esquema ajax, parabéns mesmo!

Alguns pontos que percebi que podem ser melhorados:
- Foi aprovado um PR antes e infelizmente deu conflito :/, precisa fazer aquele esquema de dar merge ou rebase e corrigir os conflitos, qualquer coisa me chama que te ajudo;
- Eu testei alguns casos com mais de um usuário e parece que algumas vezes aparecem alguns bugs, como alterar visualmente um usuário mas no momento que recarrega a página ele não foi alterado;
  - Esse erro parece aparecer quando o usuário alterado não é o primeiro, no primeiro parece funcionar perfeitamente.

2019-09-24 05:05 UTC, mateusKoppe commented on App/Models/User.php
> +            type = :type
Update sem where??

Fausto Silva: ERROOOOOUUU

2019-09-24 05:05 UTC, mateusKoppe commented on App/Views/auth/users.php
> +<?php
Sobre a view, você consegue dar uma olhada em como esta sendo feito no Events?
O objetivo no futuro é excluir o arquivo layout.php e deixar as views mais organizadas, e para isso ir utilizando as views dentro da pasta layout, (é basicamente a mesma coisa)

2019-09-24 15:22 UTC, arufonsekun commented on App/Models/User.php
> +            type = :type
não pode ser velhooo, me da um soco quando tu me encontrar

2019-09-24 15:36 UTC, arufonsekun commented on App/Models/User.php
> +            type = :type
o troxa só tinha um registro no banco

2019-09-25 00:26 UTC, arufonsekun commented on App/Views/auth/users.php
> +<?php
No  `UserController` eu chamei o `View::render()` pro _header_ e o _footer_, era isso que era pra ser feito né?

2019-09-25 00:37 UTC, mateusKoppe commented on App/Models/User.php
> +            type = :type
Eehuehueue, normal

2019-09-25 00:37 UTC, mateusKoppe commented on App/Views/auth/users.php
> +<?php
Isso mesmo ;)

2019-09-25 00:37 UTC, mateusKoppe commented
Ainda faltou corrigir o conflito, sabe como faz? (Se precisar de ajuda é só me chamar)

2019-09-25 00:40 UTC, arufonsekun commented on App/Views/auth/users.php
> +<?php
nice, o conflito vou tentar se eu precisar de ajuda eu chamo

2019-09-25 01:00 UTC, mateusKoppe requested changes

2019-09-25 01:00 UTC, mateusKoppe commented on App/Models/User.php
> +<<<<<<< HEAD
Ficou o erro aqui :/

2019-09-25 01:04 UTC, mateusKoppe commented
TOP

2019-09-25 01:05 UTC, mateusKoppe approved these changes

2019-09-25 01:05 UTC, merged