Refactor
ccuffs/sac pull request #5
Opened 2019-09-08 04:53 UTC by mateusKoppe

Cara, teve muita coisa a ser feita, listarei abaixo as melhorias que foram feitas.

- Alterei a estrutura das pastas, utilizando padrão MVC e tentando deixar o mais organizado possível;
- Implementei Url amigáveis;
- Movi o código de todas aquelas funções globais para models;
- Removi o arquivo globals que funciona com uma arquivo de comunicação entre arquivos e troquei tudo para classes e imports de outras classes, agora o único arquivo que está em escopo global é o config;
- Implementei um router (utilizando slimp-php) para chamar as funções de acordo com cada URL, esse router também facilitará a implementação de alguma API caso assim desejarmos no futuro;
- Movi aqueles arquivos que estavam na raiz do projeto para Controllers e funções dentro deles;
- Dei uma melhorada no código de vários controllers e models (porém não consegui fazer isso em todos);
- Movi as views e deixei o código delas mais amigável (antes era tudo na base do echo, agora estou fechando o php e escrevendo em html e não em string);
- Alterei a lógica de login, agora o banco de dados não armazena mais senha, agora a responsabilidade de gerir senha é feita somente com o idUffs;
- Removi a biblioteca Request que estava sendo utilizada para fazer as requisições no idUffs e utilizei funções padrões do PHP (curl);
- Implementei um helper para reutilizar o código de login usando IdUffs, no futuro será bem fácil reutilizar esse código em outros projetos;

Nem tudo está pronto mas acredito que é uma base boa para começarmos a isolar melhor as melhorias em outras issues.

2019-09-08 17:29 UTC, mateusKoppe commented
PR referente a issue #4

2019-09-12 04:40 UTC, arufonsekun requested changes

2019-09-12 04:40 UTC, arufonsekun commented on App/Config/config.php
> +<?php
Talvez o diretório que contém os arquivos de configuração do projeto poderia ficar na raiz ao invés de ficar dentro de `App`, seguindo um pouco a ideia de como o Laravel estrutura o projeto.

2019-09-12 04:40 UTC, arufonsekun commented on App/Controllers/AuthController.php
> +        AuthHelper::allowNonAuthenticated();
Os métodos estáticos `Auth::allowAuthenticated()` e `Auth::allowNonAuthenticathed()` estão sendo chamados em várias actions de vários Controllers, uma possível solução seria criar um middleware que filtre as requisições e que ele seja atrelado aos controllers a partir do `router.php`.

2019-09-12 04:40 UTC, arufonsekun commented on App/Models/Event.php
> +        $aQuery = $conn->prepare("SELECT * FROM event WHERE id = ?");
Em relação as consultas ao banco de dados, talvez a melhor abordagem seria mover esses `SQLs` para a classe `DatabaseHelper` ou até mesmo criar um novo tipo que assumisse a responsabilidade das regras de acesso ao banco de dados. Existe um padrão para isso porém ele é mais utilizado em aplicações java, nome dele é [DAO](https://pt.wikipedia.org/wiki/Objeto_de_acesso_a_dados) (Data Access Object).

2019-09-12 04:40 UTC, arufonsekun commented on App/Models/Payment.php
> +class Payment {
Outra possível abordagem além do DAO mencionado anteriormente seria criar um tipo `Model` mais genérico que se responsabilizasse pelas regras de consulta ao banco de dados, e fazer com que todos nossos models herdassem desse tipo `Model`.

2019-09-12 04:40 UTC, arufonsekun commented on App/Views/ajax-payments.php
>  $aDept 			= @$aData['dept'];
Só uma sugestão na estrutura do projeto, talvez seria interessante mover o diretório de `views` para um novo diretório chamado  `resources` seguindo o padrão do Laravel.

2019-09-13 00:47 UTC, mateusKoppe commented on App/Models/Payment.php
> +class Payment {
Bah, vai ser massa, vou criar um model e fazer isso, pelo menos umas implementações simples

2019-09-13 00:48 UTC, mateusKoppe commented on App/Views/ajax-payments.php
>  $aDept 			= @$aData['dept'];
Na real o objetivo não é imitar o laravel, e sim fazer um mvc, nesse sentido acho legal manter a view na raiz do projeto com esse nome para ficar bem claro

2019-09-13 00:48 UTC, mateusKoppe commented on App/Models/Event.php
> +        $aQuery = $conn->prepare("SELECT * FROM event WHERE id = ?");
Vou adicionar no model pai ;)

2019-09-13 00:49 UTC, mateusKoppe commented on App/Controllers/AuthController.php
> +        AuthHelper::allowNonAuthenticated();
Seria massa, mas acho melhor deixar para futuras implementações, o que acha?

2019-09-13 00:57 UTC, mateusKoppe commented on App/Config/config.php
> +<?php
Acho válido, eu vou remover a pasta config e colocar diretamente na pasta app, só para manter os arquivos php na mesma pasta, bele?

2019-09-13 11:03 UTC, arufonsekun approved these changes

2019-09-13 12:16 UTC, merged