Add more content
ccuffs/sac pull request #59
Opened 2019-10-02 04:56 UTC by mateusKoppe

Grande parte desse código é autoria de @otaudopatrick.
Se trata de um [PR](https://github.com/FronteiraTec/site-sacc-2019/pull/29) que foi aberto no [repositório anterior](https://github.com/FronteiraTec/site-sacc-2019/) da fronteiratec e eu apenas peguei o código e mandei para cá.

2019-10-02 04:56 UTC, mateusKoppe commented
Vou fechar esse PR após o merge do pr #58 para evitar possíveis conflitos já que ele altera muita coisa na home.

2019-10-02 23:53 UTC, arufonsekun approved these changes

2019-10-03 00:18 UTC, mateusKoppe commented
@arufonsekun não iria ter melhorias na redação?

2019-10-03 00:22 UTC, arufonsekun commented
sim já vai

2019-10-03 02:06 UTC, arufonsekun requested changes
Precisa de algumas mudanças no conteúdo da seção sobre a SACC

2019-10-03 02:06 UTC, arufonsekun commented on App/Views/home.php
> +            diversas áreas da computação, por meio de palestras, mesas-redondas e workshops é também uma
Vou adicionar aqui as coisas que gente conversou

2019-10-03 02:08 UTC, arufonsekun commented on App/Views/home.php
> +            diversas áreas da computação, por meio de palestras, mesas-redondas e workshops é também uma
Eu realmente não sei fazer uma code review, me dá um tiro velho

2019-10-03 15:17 UTC, arufonsekun approved these changes
Pronto pra ir pra master

2019-10-03 16:30 UTC, merged